import React, {createContext, useCallback, useContext, useEffect, useMemo, useRef, useState} from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams} from 'react-router-dom';
import content from './data/codex_game_content.json';
import musicConfig from './config/music.json';
import {buildMetroOptions} from './lib/metroOptions';
import {getDifficultyPool,validateDifficultyPools} from './config/difficultyPools';
import {selectRoundItems} from './lib/roundSelection';
import './styles/global.css';

type Difficulty='easy'|'normal'|'hard';
type Word={id:string;written:string;reading:string;pattern:string;audio:string;note:string;context?:string};
type GameData={id:number;title:string;patterns:string[];ruleOutput:Record<string,string>;levels:Record<Difficulty,Word[]>;sentenceChallenges:{id:string;text:string;audio:string;targets:{written:string;reading:string;pattern:string}[]}[]};
type RoundAnswer={id:string;original:string;context?:string;target?:string;userAnswer:string;correctAnswer:string;pronunciation:string;isCorrect:boolean};
type Result={score:number;accuracy:number;combo:number;mistakes:Record<string,number>;answers?:RoundAnswer[]};
export function getPlayerStatus(accuracy:number){if(accuracy<=40)return{label:'Юный 학생',tone:'young'};if(accuracy<=65)return{label:'Уверенный 학생',tone:'confident'};if(accuracy<=94)return{label:'학생-мастер',tone:'master'};return{label:'한글-профи',tone:'pro'} as const}
const games=content.games as unknown as GameData[];
const asset = (path: string) =>
  `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`;
const gameMeta=[
 {slug:'sound-rush',title:'Битва звуков',label:'РИТМ · РЕАКЦИЯ',cover:asset('game-covers/sound-battle.png'),key:'soundRush'},
{slug:'seoul-metro',title:'Метро Сеула',label:'МАРШРУТЫ · РЕАКЦИЯ',cover:asset('game-covers/seoul-metro.png'),key:'seoulMetro'},
{slug:'sound-battle',title:'Звуковая атака',label:'АРКАДА · РЕАКЦИЯ',cover:asset('game-covers/sound-attack.png'),key:'soundBattle'}
] as const;
const ruDiff:Record<Difficulty,string>={easy:'Легкий',normal:'Средний',hard:'Сложный'};
const gameGuides=[
  {lines:['Прочитайте слово и определите, как изменятся звуки при ассимиляции ㅂ.','Нажмите ㅁㄴ или ㅁㅁ до столкновения карточек.'],rules:['ㅂ + ㄴ → ㅁ + ㄴ','ㅂ + ㅁ → ㅁ + ㅁ','ㅂ + ㄹ → ㅁ + ㄴ'],example:'덮는 → [덤는]'},
  {lines:['Доберитесь до Сеула!','Прочитайте слово и определите, как оно произносится при ассимиляции ㄷ.','Выберите правильное чтение: нажмите на него или направьте поезд стрелками ← ↑ →.'],rules:['ㄷ + ㄴ → ㄴ + ㄴ','ㄷ + ㅁ → ㄴ + ㅁ','ㄷ + ㄹ → ㄴ + ㄴ'],example:'꽃놀이 → [꼰노리]'},
  {lines:['Прочитайте слово и определите, как изменятся звуки при ассимиляции ㄱ.','Нажмите ㅇㄴ или ㅇㅁ, чтобы атаковать правильным сочетанием звуков.'],rules:['ㄱ + ㄴ → ㅇ + ㄴ','ㄱ + ㅁ → ㅇ + ㅁ','ㄱ + ㄹ → ㅇ + ㄴ'],example:'국물 → [궁물]'}
] as const;
const readingRuleDetails=[
  {title:'АССИМИЛЯЦИЯ ㅂ',explanation:'Перед ㄴ и ㅁ звук ㅂ меняется на ㅁ. Перед ㄹ: ㄹ меняется на ㄴ, а ㅂ — на ㅁ.'},
  {title:'АССИМИЛЯЦИЯ ㄷ',explanation:'Перед ㄴ и ㅁ звук ㄷ меняется на ㄴ. Перед ㄹ оба звука произносятся как ㄴ.'},
  {title:'АССИМИЛЯЦИЯ ㄱ',explanation:'Перед ㄴ и ㅁ звук ㄱ меняется на ㅇ. Перед ㄹ: ㄹ меняется на ㄴ, а ㄱ — на ㅇ.'}
] as const;
if(import.meta.env.DEV)for(const game of games){const validation=validateDifficultyPools(game,game.id);if(validation.duplicates.length||validation.empty.length)console.error('Ошибка распределения сложности',game.id,validation)}
const readStore=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)??'') as T}catch{return fallback}};
const splitAssimilation=(written:string,pattern:string):[string,string]=>{const onset=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];const finals=['','ㄱ','ㄲ','ㄳ','ㄴ','ㄵ','ㄶ','ㄷ','ㄹ','ㄺ','ㄻ','ㄼ','ㄽ','ㄾ','ㄿ','ㅀ','ㅁ','ㅂ','ㅄ','ㅅ','ㅆ','ㅇ','ㅈ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];const labials=new Set(['ㅂ','ㅄ','ㄼ','ㄿ','ㅍ']);const next=pattern[pattern.length-1];for(let i=0;i<written.length-1;i++){const code=written.charCodeAt(i)-0xac00;if(code<0||code>11171)continue;const final=finals[code%28];let j=i+1;while(written[j]===' ')j++;const nextCode=written.charCodeAt(j)-0xac00;if(labials.has(final)&&nextCode>=0&&nextCode<=11171&&onset[Math.floor(nextCode/588)]===next)return[written.slice(0,i+1).trim(),written.slice(j).trim()]}const pivot=Math.max(1,Math.floor(written.length/2));return[written.slice(0,pivot).trim(),written.slice(pivot).trim()]};
export const getDisplaySplit=(target:string,pattern:string):[string,string]=>{const numericTarget=target.match(/^(\d+)(.+)$/u);if(numericTarget)return[numericTarget[1],numericTarget[2].trim()];return splitAssimilation(target,pattern)};

type AudioCtx={muted:boolean;toggle:()=>void;playSfx:(n:string)=>void;speak:(text:string,file?:string)=>void;bossMode:(on:boolean)=>void};
const AudioContext=createContext<AudioCtx>({muted:false,toggle:()=>{},playSfx:()=>{},speak:()=>{},bossMode:()=>{}});
type MusicKey='home'|'soundRush'|'seoulMetro'|'soundBattle'|'boss';
const musicForPath=(path:string):MusicKey=>{
  if(path==='/sound-rush'||path==='/game/sound-rush'||path.startsWith('/result/1/'))return 'soundRush';
  if(path==='/seoul-metro'||path==='/game/seoul-metro'||path.startsWith('/result/2/'))return 'seoulMetro';
  if(path==='/sound-battle'||path==='/game/sound-battle'||path.startsWith('/result/3/'))return 'soundBattle';
  return 'home';
};
function AudioProvider({children}:{children:React.ReactNode}){
  const [muted,setMuted]=useState(()=>readStore<boolean>('ks-audio-muted',false)===true);const music=useRef<HTMLAudioElement|null>(null);const activeFile=useRef('');const fadeTimer=useRef<ReturnType<typeof setInterval>|null>(null);const transition=useRef(0);const mutedRef=useRef(muted);const pathRef=useRef('/');const location=useLocation();
  pathRef.current=location.pathname;mutedRef.current=muted;
  const toggle=()=>setMuted(v=>{localStorage.setItem('ks-audio-muted',JSON.stringify(!v));return !v});
  const fadeTo=useCallback((audio:HTMLAudioElement,target:number,duration:number,token:number,done?:()=>void)=>{if(fadeTimer.current)clearInterval(fadeTimer.current);const start=audio.volume;const begun=performance.now();fadeTimer.current=setInterval(()=>{if(token!==transition.current){if(fadeTimer.current)clearInterval(fadeTimer.current);return}const ratio=Math.min(1,(performance.now()-begun)/Math.max(1,duration));audio.volume=Math.max(0,Math.min(1,start+(target-start)*ratio));if(ratio>=1){if(fadeTimer.current)clearInterval(fadeTimer.current);fadeTimer.current=null;done?.()}},25)},[]);
  const switchTrack=useCallback((key:MusicKey)=>{const cfg=musicConfig[key];if(activeFile.current===cfg.file)return;const audio=music.current??new Audio();music.current=audio;audio.loop=cfg.loop;const token=++transition.current;const begin=()=>{if(token!==transition.current)return;audio.pause();audio.src = `${import.meta.env.BASE_URL}${cfg.file.replace(/^\/+/, '')}`;audio.loop=cfg.loop;audio.currentTime=0;audio.volume=0;activeFile.current=cfg.file;audio.load();if(mutedRef.current)return;audio.play().then(()=>fadeTo(audio,.42,cfg.fadeMs,token)).catch(()=>{audio.volume=.42})};if(activeFile.current&&!audio.paused&&audio.volume>0)fadeTo(audio,0,Math.min(cfg.fadeMs,320),token,begin);else begin()},[fadeTo]);
  const routeKey=musicForPath(location.pathname);
  useEffect(()=>{switchTrack(routeKey)},[routeKey,switchTrack]);
  useEffect(()=>{const audio=music.current;if(!audio)return;if(muted){audio.pause()}else{audio.volume=Math.max(audio.volume,.42);audio.play().catch(()=>{})}},[muted]);
  useEffect(()=>{const resume=()=>{const audio=music.current;if(!mutedRef.current&&audio?.paused){audio.volume=Math.max(audio.volume,.42);audio.play().catch(()=>{})}};addEventListener('pointerdown',resume);addEventListener('keydown',resume);return()=>{removeEventListener('pointerdown',resume);removeEventListener('keydown',resume);if(fadeTimer.current)clearInterval(fadeTimer.current);music.current?.pause()}},[]);
  const playSfx=useCallback((n:string)=>{if(!muted){const a=new Audio(`${import.meta.env.BASE_URL}sfx/${n}.mp3`);a.volume=.7;a.play().catch(()=>{})}},[muted]);
  const speak=useCallback((text:string)=>{if(mutedRef.current)return;const bg=music.current;const token=transition.current;const restore=()=>{if(bg&&activeFile.current)fadeTo(bg,.42,musicConfig.ducking.releaseMs,token)};if(bg)fadeTo(bg,.167,musicConfig.ducking.attackMs,token);try{if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){restore();return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.onend=restore;u.onerror=restore;speechSynthesis.speak(u)}catch{restore()}},[fadeTo]);
  const bossMode=useCallback((on:boolean)=>{switchTrack(on?'boss':musicForPath(pathRef.current))},[switchTrack]);
  return <AudioContext.Provider value={{muted,toggle,playSfx,speak,bossMode}}>{children}</AudioContext.Provider>
}

function Header({home=false,game=false}:{home?:boolean;game?:boolean}){const {muted,toggle}=useContext(AudioContext);return <header className={`${home?'home-header ':''}${game?'game-header':''}`}><Link to="/" className="brand"><img src={asset('brand/logo.png')} alt=""/><span>Корейский словарик</span></Link>{home&&<div className="header-title"><span className="header-title-ko">한글</span><span className="header-title-ru">: Ассимиляция</span></div>}<button className="sound" onClick={toggle} aria-label="Переключить звук">{muted?'🔇':'🔊'}</button></header>}
function Home(){return <main className="home"><Header home/><section id="games" className="cards">{games.map((g,i)=><article className={`game-card c${i+1}`} key={g.id} aria-label={gameMeta[i].title} style={{backgroundImage:`url("${gameMeta[i].cover}")`}}><div className="card-body"><div className="card-foot"><span>Рекорд <b>{bestFor(i+1)}</b></span><Link to={`/${gameMeta[i].slug}`} className="play">Играть <b>→</b></Link></div></div></article>)}</section></main>}
function bestFor(id:number){return Math.max(0,...(['easy','normal','hard'] as Difficulty[]).map(d=>readStore<Result>(`ks-result-${id}-${d}`,{score:0,accuracy:0,combo:0,mistakes:{}}).score)).toLocaleString('ru-RU')}

function ReadingRulesModal({gameId,onChooseLevel}:{gameId:number;onChooseLevel:()=>void}){const [open,setOpen]=useState(false);const guide=gameGuides[gameId-1];const details=readingRuleDetails[gameId-1];useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[open]);const chooseLevel=()=>{setOpen(false);onChooseLevel()};return <><button className="rules-trigger" aria-expanded={open} onClick={()=>setOpen(true)}>Правила чтения</button>{open&&<div className="reading-rules-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="reading-rules-modal" role="dialog" aria-modal="true" aria-labelledby="reading-rules-title"><button className="reading-rules-close" aria-label="Закрыть" onClick={()=>setOpen(false)}>×</button><div className="reading-rules-content"><h2 id="reading-rules-title">{details.title}</h2><div className="reading-rules-formulas">{guide.rules.map(rule=><b key={rule}>{rule}</b>)}</div><strong className="reading-rules-example">{guide.example}</strong><p>{details.explanation}</p><div className="reading-rules-actions"><button className="reading-rules-level" onClick={chooseLevel}>Выбрать уровень</button></div></div></section></div>}</>}
function HowToPlay({game,onContinue}:{game:GameData;onContinue:()=>void}){const guide=gameGuides[game.id-1];return <div className={`overlay guide-screen theme-${game.id}`}><div className="guide-shell"><h1>{gameMeta[game.id-1].title}</h1><div className="difficulty-patterns">{game.patterns.map(pattern=><span key={pattern}>{pattern}</span>)}</div><section className="guide-grid"><div className="guide-instructions"><h2>КАК ИГРАТЬ</h2>{guide.lines.map(line=><p key={line}>{line}</p>)}</div></section><ReadingRulesModal gameId={game.id} onChooseLevel={onContinue}/><button className="guide-continue" onClick={onContinue}>Выбрать уровень</button><Link className="guide-home" to="/">← На главную</Link></div></div>}
function DifficultyPicker({game,onStart}:{game:GameData;onStart:(d:Difficulty)=>void}){const saved=readStore<unknown>('ks-last-difficulty','easy');const last:Difficulty=saved==='normal'||saved==='hard'?saved:'easy';const descriptions:Record<Difficulty,string>={easy:'Подсказки · медленный темп',normal:'Без подсказок · обычный темп',hard:'Сначала звук · предложения'};return <div className={`overlay difficulty-screen theme-${game.id}`}><div className="difficulty-shell"><h1>{gameMeta[game.id-1].title}</h1><div className="difficulty-patterns">{game.patterns.map(p=><span key={p}>{p}</span>)}</div><p className="difficulty-prompt">Выбери уровень</p><div className="difficulty">{(['easy','normal','hard'] as Difficulty[]).map((d,index)=><button key={d} className={`${d} ${d===last?'active':''}`} onClick={()=>onStart(d)}><span className="level-dots" aria-hidden="true">{[0,1,2].map(n=><i className={n<=index?'on':''} key={n}/>)}</span><b>{ruDiff[d]}</b><small>{descriptions[d]}</small></button>)}</div><Link className="difficulty-home" to="/">← На главную</Link></div></div>}
function Hud({score,combo,lives,metro=false,progress=0}:{score:number;combo:number;lives:number;energy:number;label:string;rush:boolean;metro?:boolean;progress?:number}){return <div className={`hud floating-hud ${metro?'metro-hud':''}`}><div><small>ОЧКИ</small><b>{score.toLocaleString('ru-RU')}</b></div><div><small>СЕРИЯ</small><b>×{combo}</b></div>{metro&&<div className="metro-line" aria-label={`Прогресс: ${Math.round(progress)}%`}>{[0,1,2,3,4].map(n=><React.Fragment key={n}><i className={progress>=n*25?'passed':''}/>{n<4&&<span/>}</React.Fragment>)}</div>}<div className="lives"><small>ЖИЗНИ</small><span className="hearts" aria-label={`Жизни: ${lives}`}>{'♥'.repeat(lives)}<i>{'♥'.repeat(3-lives)}</i></span></div></div>}
function GamePage(){const {slug}=useParams();const idx=gameMeta.findIndex(m=>m.slug===slug);const nav=useNavigate();const {playSfx,speak,bossMode}=useContext(AudioContext);const game=games[idx];const [showDifficulty,setShowDifficulty]=useState(false);const [difficulty,setDifficulty]=useState<Difficulty|null>(null);const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [combo,setCombo]=useState(0);const [maxCombo,setMaxCombo]=useState(0);const [lives,setLives]=useState(3);const [hits,setHits]=useState(0);const [energy,setEnergy]=useState(0);const [feedback,setFeedback]=useState('');const [mistakes,setMistakes]=useState<Record<string,number>>({});const [roundAnswers,setRoundAnswers]=useState<RoundAnswer[]>([]);const [paused,setPaused]=useState(false);const [boss,setBoss]=useState(false);const [bossHp,setBossHp]=useState(5);const [battleEffect,setBattleEffect]=useState<'correct'|'wrong'|null>(null);const [battleRune,setBattleRune]=useState(0);const [rushEffect,setRushEffect]=useState<'correct'|'wrong'|null>(null);const [metroEffect,setMetroEffect]=useState<'correct'|'wrong'|null>(null);const [metroDirection,setMetroDirection]=useState(1);const [hintOpen,setHintOpen]=useState(false); const answered=useRef(false);const wordStarted=useRef(Date.now());const actionTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [roundItems,setRoundItems]=useState<Word[]>([]);const words=roundItems;const total=words.length;const bossWords=(content.boss.targets.filter(t=>t.game===3).map((t,i)=>({id:`boss-${i}`,written:t.written,reading:t.reading,pattern:t.pattern,audio:'',note:content.boss.title})) as Word[]);const word=boss?bossWords[round%bossWords.length]:words[round%Math.max(1,words.length)];
  const finish=useCallback((finalOk=0,finalGain=0,finalPattern?:string,answers=roundAnswers)=>{const finalMistakes=finalPattern?{...mistakes,[finalPattern]:(mistakes[finalPattern]||0)+1}:mistakes;const accuracy=Math.round((hits+finalOk)/Math.max(1,boss?5:round+1)*100);const result:Result={score:score+finalGain,accuracy,combo:Math.max(maxCombo,combo+finalOk),mistakes:finalMistakes,answers};const key=`ks-result-${game.id}-${difficulty}`;const old=readStore<Result>(key,{score:0,accuracy:0,combo:0,mistakes:{}});if(result.score>old.score)localStorage.setItem(key,JSON.stringify(result));localStorage.setItem('ks-hard-unlocked','true');playSfx('victory');nav(`/result/${game.id}/${difficulty}`,{state:result})},[hits,round,score,maxCombo,combo,mistakes,roundAnswers,boss,game.id,difficulty,playSfx,nav]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setPaused(p=>!p);if(paused||!difficulty)return;if(idx===0&&['1','ArrowLeft'].includes(e.key))answer(0);if(idx===0&&['2','ArrowRight'].includes(e.key))answer(1);if(idx===1){if(['ArrowLeft','a','A'].includes(e.key))answer(0);if(['ArrowUp','w','W'].includes(e.key))answer(1);if(['ArrowRight','d','D'].includes(e.key))answer(2)}if(idx===2){if(e.key==='1')answer(0);if(e.key==='2')answer(1)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
  useEffect(()=>{answered.current=false;wordStarted.current=Date.now();setHintOpen(false);if(!difficulty||paused||idx!==0)return;const timeout=setTimeout(()=>answer(-1),difficulty==='easy'?5200:difficulty==='normal'?4100:3200);return()=>clearTimeout(timeout)},[round,difficulty,paused]);
  useEffect(()=>{if(boss){bossMode(true);playSfx('boss-warning')}return()=>{if(boss)bossMode(false)}},[boss]);
  useEffect(()=>()=>{if(actionTimer.current)clearTimeout(actionTimer.current)},[]);
  const metroPool=useMemo(()=>idx===1?words:[],[words,idx]);
  const metroOpts=useMemo(()=>idx===1&&word?buildMetroOptions(word,metroPool):[],[idx,word?.id,round,metroPool]);
  function startRound(d:Difficulty){const pool=getDifficultyPool(game,idx+1,d) as Word[];const historyKey=`ks-previous-round:${game.id}:${d}`;const previous=readStore<string[]>(historyKey,[]);const selected=selectRoundItems(pool,6,previous);localStorage.setItem(historyKey,JSON.stringify(selected.map(item=>item.id)));localStorage.setItem('ks-last-difficulty',d);setRoundItems(selected);setDifficulty(d);playSfx('game-start')}
  if(!game)return <Home/>;if(!difficulty)return <><Header/>{showDifficulty?<DifficultyPicker game={game} onStart={startRound}/>:<HowToPlay game={game} onContinue={()=>setShowDifficulty(true)}/>}</>;
  function options(){const all=Array.from(new Set(Object.values(game.ruleOutput).map(v=>v.replace('+',''))));if(idx===0)return ['ㅁㄴ','ㅁㅁ'];if(idx===1)return metroOpts;if(idx===2)return ['ㅇㅁ','ㅇㄴ'];return all.length>1?all:['ㅁㅁ','ㅁㄴ']}
  const opts=options(); const expected=idx===1?word.reading:game.ruleOutput[word.pattern].replace('+','');const correct=opts.indexOf(expected);
  function answer(choice:number){if(answered.current||paused)return;answered.current=true;const ok=choice===correct;const nextCombo=ok?combo+1:0;const elapsed=Date.now()-wordStarted.current;const perfect=idx===0&&elapsed>2600&&elapsed<4300;const transfer=idx===1&&combo>=3&&(round+1)%4===0;const gain=ok?(idx===0?(perfect?180:110):transfer?250:150)*(energy>=100?2:1):0;const recorded:RoundAnswer={id:`${word.id}-${roundAnswers.length}`,original:word.written,context:word.context,target:word.written,userAnswer:choice>=0&&opts[choice]?opts[choice]:'—',correctAnswer:expected,pronunciation:word.reading,isCorrect:ok};const nextAnswers=[...roundAnswers,recorded];setRoundAnswers(nextAnswers);if(idx===0){setRushEffect(ok?'correct':'wrong');setFeedback('')}if(idx===1){setMetroDirection(choice);setMetroEffect(ok?'correct':'wrong');setFeedback('')}if(idx===2){setBattleRune(choice);setBattleEffect(ok?'correct':'wrong');setFeedback('')}setCombo(nextCombo);setMaxCombo(Math.max(maxCombo,nextCombo));setScore(s=>s+gain);setHits(h=>h+(ok?1:0));setEnergy(e=>ok?Math.min(100,e+14):Math.max(0,e-25));if(ok){playSfx(idx===0?(perfect?'perfect':'correct'):idx===1?'train-pass':boss?'boss-hit':'hit');speak(word.reading,word.audio||undefined);if(boss)setBossHp(h=>h-1)}else{setLives(l=>l-1);setMistakes(m=>({...m,[word.pattern]:(m[word.pattern]||0)+1}));playSfx('heart-loss')}
    actionTimer.current=setTimeout(()=>{setFeedback('');setBattleEffect(null);setRushEffect(null);setMetroEffect(null);if((!ok&&lives<=1)||(boss&&ok&&bossHp<=1))finish(ok?1:0,gain,ok?undefined:word.pattern,nextAnswers);else if(idx===2&&!boss&&round+1>=total){setBoss(true);setRound(0);setHits(0);setLives(3)}else if(!boss&&round+1>=total)finish(ok?1:0,gain,ok?undefined:word.pattern,nextAnswers);else{setRound(r=>r+1);answered.current=false}},idx===2?2000:idx===1?5000:900)}
  const progress=boss?((5-bossHp)/5)*100:((round+1)/total)*100;const isLab=idx===1&&word.pattern==='ㄷ+ㄹ';const transfer=idx===1&&combo>=3&&(round+1)%4===0;return <main className={`game game-${idx+1} ${energy>=100?'fever':''}`}><Header game/><div className="progress"><i style={{width:`${progress}%`}}/></div><Hud score={score} combo={combo} lives={lives} energy={energy} rush={idx===0} metro={idx===1} progress={progress} label=""/>{idx===0&&<Rush word={word} options={opts} choose={answer} difficulty={difficulty} effect={rushEffect} hintOpen={hintOpen} toggleHint={()=>setHintOpen(v=>!v)} hint={`${word.pattern.replace('+',' + ')} = ${game.ruleOutput[word.pattern].replace('+',' + ')}`}/>} {idx===1&&<Metro word={word} options={opts} choose={answer} effect={metroEffect} direction={metroDirection} difficulty={difficulty} combo={combo} transfer={transfer||isLab} hintOpen={hintOpen} toggleHint={()=>setHintOpen(v=>!v)} hint={`${word.pattern.replace('+',' + ')} → ${game.ruleOutput[word.pattern].replace('+',' + ')}`}/>} {idx===2&&<Battle word={word} options={opts} choose={answer} boss={boss} hp={bossHp} effect={battleEffect} rune={battleRune} easy={difficulty==='easy'} answers={roundAnswers} hintOpen={hintOpen} toggleHint={()=>setHintOpen(v=>!v)} hint={`${word.pattern.replace('+',' + ')} → ${game.ruleOutput[word.pattern].replace('+',' + ')}`}/>} {paused&&<div className="pause overlay"><div className="modal"><h1>Пауза</h1><button className="play" onClick={()=>setPaused(false)}>Продолжить</button><Link to="/">На главную</Link></div></div>}</main>}

function Rush({word,options,choose,difficulty,effect,hintOpen,toggleHint,hint}:{word:Word;options:string[];choose:(n:number)=>void;difficulty:Difficulty;effect:'correct'|'wrong'|null;hintOpen:boolean;toggleHint:()=>void;hint:string}){const [left,right]=getDisplaySplit(word.written,word.pattern);const parts=word.context?word.context.split(word.written):[];return <section className={`arena rush fusion-rush ${difficulty} ${effect?`fusion-${effect}`:''}`}>{word.context&&<p className="rush-context">{parts.map((part,index)=><React.Fragment key={`${part}-${index}`}>{part}{index<parts.length-1&&<mark>{word.written}</mark>}</React.Fragment>)}</p>}<div className="fusion-stage" key={word.id}><div className="sound-half sound-left"><b>{left}</b></div><div className="fusion-core" aria-hidden="true"><i/><span/><em/></div><div className="sound-half sound-right"><b>{right}</b></div>{effect==='correct'&&<div className="fusion-result">[{word.reading}]</div>}{effect==='wrong'&&<div className="rush-particles">{Array.from({length:12},(_,i)=><i key={i}/>)}</div>}</div>{difficulty==='easy'&&<div className="rush-hint-wrap"><button className="hint-button" onClick={toggleHint}>Подсказка</button>{hintOpen&&<div className="hint-popover">{hint.replace(' = ',' → ')}</div>}</div>}<div className="runes rush-runes">{options.map((o,i)=><button key={o} onClick={()=>choose(i)} aria-label={o}><b>{o}</b></button>)}</div></section>}
function Metro({word,options,choose,effect,direction,difficulty,combo,transfer,hintOpen,toggleHint,hint}:{word:Word;options:string[];choose:(n:number)=>void;effect:'correct'|'wrong'|null;direction:number;difficulty:Difficulty;combo:number;transfer:boolean;hintOpen:boolean;toggleHint:()=>void;hint:string}){const touch=useRef<{x:number;y:number}|null>(null);const parts=word.context?word.context.split(word.written):[];const isResolving=effect!==null;const metroVideo=effect
  ? [
      asset('seoul-metro/metro-left.mp4'),
      asset('seoul-metro/metro-straight.mp4'),
      asset('seoul-metro/metro-right.mp4')
    ][direction]
  : asset('seoul-metro/metro-approach.mp4');
  const selectRoute=(index:number)=>{if(!isResolving)choose(index)};const pickSwipe=(x:number,y:number)=>{const start=touch.current;if(!start)return;const dx=x-start.x,dy=y-start.y;touch.current=null;if(Math.max(Math.abs(dx),Math.abs(dy))<34)return;if(Math.abs(dx)>Math.abs(dy))selectRoute(dx<0?0:2);else if(dy<0)selectRoute(1)};return <section className={`arena metro metro-run ${difficulty} combo-${Math.min(combo,8)} ${transfer?'metro-transfer':''} ${effect?`metro-${effect} metro-turn-${direction}`:''}`} onPointerDown={e=>{touch.current={x:e.clientX,y:e.clientY}}} onPointerUp={e=>pickSwipe(e.clientX,e.clientY)}><div className="metro-camera">
  <video
    key={`${word.id}-${effect ?? 'approach'}-${direction}`}
    className="metro-video"
    src={metroVideo}
    poster={asset('seoul-metro/tunnel-race.png')}
    autoPlay
    muted
    playsInline
    preload="auto"
  />
  <div className="metro-video-shade"/>
  <div className="metro-speed-lines"/>
    <div className="metro-track-glow"/><div className="metro-junction" key={word.id}>{options.map((option,index)=><button type="button" disabled={isResolving} onClick={()=>selectRoute(index)} aria-label={`Маршрут ${['влево','прямо','вправо'][index]}: ${option}`} className={`metro-route route-${index} ${effect&&direction===index?'selected':''}`} key={`${word.id}-${option}`}><span aria-hidden="true">{['←','↑','→'][index]}</span><b>[{option}]</b></button>)}</div></div>{word.context&&<p className="metro-context">{parts.map((part,index)=><React.Fragment key={`${part}-${index}`}>{part}{index<parts.length-1&&<mark>{word.written}</mark>}</React.Fragment>)}</p>}{!word.context&&<div className="metro-word"><b>{word.written}</b>{transfer&&<small>{word.pattern==='ㄷ+ㄹ'?'Звуковая лаборатория':'Пересадка'}</small>}</div>}{difficulty==='easy'&&<div className="metro-hint"><button className="hint-button" onClick={toggleHint}>Подсказка</button>{hintOpen&&<div className="hint-popover">{hint}</div>}</div>}{effect==='correct'&&<div className="metro-reading">{word.written} → [{word.reading}]</div>}{effect==='wrong'&&<><div className="emergency-board">{word.written} → [{word.reading}]</div><div className="metro-sparks" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i}/>)}</div></>}<div className="metro-controls" aria-hidden="true"><span>←</span><span>↑</span><span>→</span></div></section>}
function Battle({word,options,choose,boss,effect,rune,easy,answers,hintOpen,toggleHint,hint}:{word:Word;options:string[];choose:(n:number)=>void;boss:boolean;hp:number;effect:'correct'|'wrong'|null;rune:number;easy:boolean;answers:RoundAnswer[];hintOpen:boolean;toggleHint:()=>void;hint:string}){
  const context=word.context;const parts=context?context.split(word.written):[];const settled=effect?answers.slice(0,-1):answers;
  const arenaRef=useRef<HTMLElement>(null);const enemyRef=useRef<HTMLDivElement>(null);const runeRefs=useRef<(HTMLButtonElement|null)[]>([]);const [beam,setBeam]=useState<{left:number;top:number;width:number;angle:number}|null>(null);
  useEffect(()=>{if(!effect){setBeam(null);return}const measure=()=>{const arena=arenaRef.current,button=runeRefs.current[rune],enemy=enemyRef.current;if(!arena||!button||!enemy)return;const arenaBox=arena.getBoundingClientRect(),start=button.getBoundingClientRect(),target=(enemy.querySelector('mark')||enemy).getBoundingClientRect();const left=start.left+start.width/2-arenaBox.left,top=start.top+start.height/2-arenaBox.top,endX=target.left+target.width/2-arenaBox.left,endY=target.top+target.height/2-arenaBox.top,dx=endX-left,dy=endY-top;setBeam({left,top,width:Math.hypot(dx,dy),angle:Math.atan2(dy,dx)*180/Math.PI})};const frame=requestAnimationFrame(measure);addEventListener('resize',measure);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',measure)}},[effect,rune,word.id]);
  const collection=(correct:boolean)=>{const matching=settled.filter(answer=>answer.isCorrect===correct);const visible=matching.slice(-6);return <aside className={`battle-collection ${correct?'collection-correct':'collection-wrong'}`} aria-label={correct?'Верные ответы':'Ошибки'}>{matching.length>visible.length&&<div className="collection-more">+{matching.length-visible.length}</div>}{visible.map(answer=><div className="collected-card" key={answer.id}><i>{correct?'✓':'✕'}</i><span><b>{answer.target||answer.original}</b><small>[{answer.pronunciation}]</small></span></div>)}</aside>};
  return <section ref={arenaRef} className={`arena battle ${effect?`battle-${effect}`:''}`}>{collection(false)}{collection(true)}<div ref={enemyRef} className={`enemy ${boss?'boss':''} ${effect==='correct'?'enemy-collected':effect==='wrong'?'enemy-burned':''}`}>{context?<p className="battle-context">{parts.map((part,index)=><React.Fragment key={`${part}-${index}`}>{part}{index<parts.length-1&&<mark>{word.written}</mark>}</React.Fragment>)}</p>:<><b>{word.written}</b><span>{word.pattern.replace('+',' + ')}</span></>}</div>{effect&&<div className={`battle-flight-card flight-${effect}`}><b>{word.written}</b><small>[{word.reading}]</small></div>}{effect&&beam&&<div key={`${word.id}-${effect}-${rune}`} className={`battle-laser laser-${rune} ${effect}`} style={{left:beam.left,top:beam.top,width:beam.width,'--beam-angle':`${beam.angle}deg`} as React.CSSProperties}>{Array.from({length:12},(_,index)=><i key={index}/>)}</div>}<div className="battle-vault" aria-hidden="true"><span>✓</span></div>{easy&&<div className="hint-wrap"><button className="hint-button" onClick={toggleHint}>Подсказка</button>{hintOpen&&<div className="hint-popover">{hint}</div>}</div>}<div className="runes battle-runes">{options.map((o,i)=><button ref={element=>{runeRefs.current[i]=element}} key={o} disabled={Boolean(effect)} onClick={()=>choose(i)} className={effect&&rune===i?'rune-fired':''}><kbd>{i+1}</kbd><b>{o}</b></button>)}</div></section>
}
function Feedback({text}:{text:string}){return text?<div className={`feedback ${text.startsWith('아니요')?'bad':''}`}>{text}</div>:null}
function AnswersReview({answers}:{answers:RoundAnswer[]}){const [open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';addEventListener('keydown',close);return()=>{document.body.style.overflow=previousOverflow;removeEventListener('keydown',close)}},[open]);const correct=answers.filter(answer=>answer.isCorrect).length;return <><button className="review-button" onClick={()=>setOpen(true)}>Мои ответы</button>{open&&<div className="answers-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="answers-review" role="dialog" aria-modal="true" aria-labelledby="answers-title"><button className="answers-close" aria-label="Закрыть" onClick={()=>setOpen(false)}>×</button><div className="answers-heading"><h2 id="answers-title">Мои ответы</h2><p className="answers-total">{answers.length} заданий · {correct} верно · {answers.length-correct} ошибки</p></div><div className="answers-columns" aria-hidden="true"><b>Мои ответы</b><b>Произношение</b></div><div className="answers-list">{answers.length?answers.map((answer,index)=><article className={answer.isCorrect?'answer-correct':'answer-wrong'} key={`${answer.id}-${index}`}><div className="answer-response"><strong><i>{answer.isCorrect?'✓':'✕'}</i>{answer.target||answer.original}</strong>{answer.context&&<small>{answer.context}</small>}{answer.isCorrect?<div className="answer-choice">{answer.userAnswer}</div>:<div className="answer-correction"><span>Вы выбрали: <b>{answer.userAnswer}</b></span><span>Правильно: <b>{answer.correctAnswer}</b></span></div>}</div><span className="answer-pronunciation">[{answer.pronunciation}]</span></article>):<p className="answers-empty">В этом раунде пока нет ответов.</p>}</div></section></div>}</>}
function ResultPage(){const {id,difficulty}=useParams();const nav=useNavigate();const raw=history.state?.usr||readStore<unknown>(`ks-result-${id}-${difficulty}`,{});const candidate=raw&&typeof raw==='object'?raw as Partial<Result>:{};const state:Result={score:typeof candidate.score==='number'?candidate.score:0,accuracy:typeof candidate.accuracy==='number'?candidate.accuracy:0,combo:typeof candidate.combo==='number'?candidate.combo:0,mistakes:candidate.mistakes&&typeof candidate.mistakes==='object'?candidate.mistakes:{},answers:Array.isArray(candidate.answers)?candidate.answers:[]};const status=getPlayerStatus(state.accuracy);const next=Number(id)%3;const repeat=Object.entries(state.mistakes).filter(([,count])=>count>0).map(([pattern])=>pattern);const errors=Object.values(state.mistakes).reduce((a,b)=>a+b,0);return <main className={`result theme-${id}`}><Header/><div className={`result-card status-${status.tone}`}><small>РАУНД ЗАВЕРШЁН</small><div className="result-summary"><div className="rank"><span>{state.accuracy}<small>%</small></span></div><h1 className="player-status">{status.label}</h1><div className="score-block"><h2>{state.score.toLocaleString('ru-RU')} <b>очков</b></h2></div></div><div className="result-grid"><span>Точность <b>{state.accuracy}%</b></span><span>Лучшая серия <b>×{state.combo}</b></span><span>Ошибки <b>{errors}</b></span></div>{repeat.length>0&&<p className="repeat-patterns">Повтори: <b>{repeat.join(' · ')}</b></p>}<div className="actions"><button className="retry" onClick={()=>nav(`/${gameMeta[Number(id)-1].slug}`)}>Ещё раз</button><button className="next" onClick={()=>nav(`/${gameMeta[next].slug}`)}>Следующая игра</button><AnswersReview answers={state.answers||[]}/><Link to="/">На главную</Link></div></div></main>}
class RuntimeErrorBoundary extends React.Component<{children:React.ReactNode},{error:Error|null}>{state:{error:Error|null}={error:null};static getDerivedStateFromError(error:Error){return{error}}componentDidCatch(error:Error,info:React.ErrorInfo){console.error('Ошибка игры',error,info.componentStack)}render(){if(this.state.error)return <main className="runtime-error"><div><span className="eyebrow">ОШИБКА</span><h1>Игра остановлена</h1><p>Перезагрузите страницу и попробуйте снова.</p><button onClick={()=>location.reload()}>Перезагрузить</button><Link to="/">На главную</Link></div></main>;return this.props.children}}
function App(){return <AudioProvider><RuntimeErrorBoundary><Routes><Route path="/" element={<Home/>}/><Route path="/:slug" element={<GamePage/>}/><Route path="/game/:slug" element={<GamePage/>}/><Route path="/result/:id/:difficulty" element={<ResultPage/>}/><Route path="*" element={<Home/>}/></Routes></RuntimeErrorBoundary></AudioProvider>}
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter basename={import.meta.env.BASE_URL}>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
